KS-2-5 commit
decalsheggy/KotlinSprint pull request #10
Opened 2024-04-04 12:50 UTC by decalsheggy

2024-04-06 07:04 UTC, ievetrovdev requested changes

2024-04-06 07:04 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2-task5.kt
> +    val s = p * ((1+i).pow(n))
Однобуквенные переменные - зло, они уместны только в циклах в качестве интерируемой переменной, в остальном - теряется контекст в месте использования переменной. Давай дадим понятное название.

Напоминаю, все арифметические знаки обосабливаются пробелами.
В IDEA есть автоформатирование кода: Находясь в файле Ctrl+Alt+L (для windows) или ⌥+⌘+L (для osx). Рекомендую взять в привычку прожимать автоформат всегда перед коммитом, чтобы все отступы и пробелы расставить по своим местам.

2024-04-06 07:21 UTC, decalsheggy commented on src/main/kotlin/lesson2/lesson2-task5.kt
> +    val s = p * ((1+i).pow(n))
Хорошо, поняла

2024-04-07 07:49 UTC, ievetrovdev approved these changes
Отлично!

2024-04-08 04:09 UTC, merged