KS-21-5 commit
decalsheggy/KotlinSprint pull request #105
Opened 2024-05-15 19:01 UTC by decalsheggy

2024-05-17 04:27 UTC, ievetrovdev requested changes

2024-05-17 04:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson21-task5.kt
> +fun Map<String, Int>.maxCategory(): String? {
Вроде достаточно сделать просто `fun Map<String, Int>.maxCategory() = maxByOrNull { it.value }?.key`)

2024-05-17 09:20 UTC, decalsheggy commented on src/main/kotlin/lesson_21/lesson21-task5.kt
> +fun Map<String, Int>.maxCategory(): String? {
А как тогда можно вернуть рандомный ключ среди нескольких одинаковых максимальных значений?..

2024-05-18 07:26 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson21-task5.kt
> +fun Map<String, Int>.maxCategory(): String? {
Да, в данном случае будет всегда возвращено первое значение, но в этом задании это не критично)

2024-05-18 07:26 UTC, ievetrovdev approved these changes

2024-05-19 10:59 UTC, merged