KS-3-2 commit
decalsheggy/KotlinSprint pull request #12
Opened 2024-04-04 14:28 UTC by decalsheggy

2024-04-05 07:45 UTC, ievetrovdev requested changes

2024-04-05 07:45 UTC, ievetrovdev commented on src/main/kotlin/lesson_3/lesson3-task2.kt
> +    val beforeWeddingName = "Андреева Татьяна Сергеевна"
Опять же не по ТЗ
Все части ФИО и возраст изначально хранятся в отдельных переменных
Читай внимательнее, в будущей работе это важно

2024-04-05 08:27 UTC, decalsheggy commented on src/main/kotlin/lesson_3/lesson3-task2.kt
> +    val beforeWeddingName = "Андреева Татьяна Сергеевна"
Спасибо, постараюсь быть внимательнее

2024-04-05 15:51 UTC, ievetrovdev requested changes

2024-04-05 15:51 UTC, ievetrovdev commented on src/main/kotlin/lesson_3/lesson3-task2.kt
> +    val ageBeforeWedding = 20
Проинициализированные данные мы принимаем за "сущность". Пока что не забегаем вперед, но такое дублирование переменных не очень правильный тон (представь, что таких смен фамилий будет 50 шт условно). Поэтому мы исходные переменные оставляем как есть, но потом перезаписываем в них данные. Поэтому распечатываем сначала то, что есть, а затем меняем данные в переменных и отображаем снова.

2024-04-05 16:34 UTC, decalsheggy commented on src/main/kotlin/lesson_3/lesson3-task2.kt
> +    val ageBeforeWedding = 20
Исправила

2024-04-06 06:02 UTC, ievetrovdev approved these changes
Да, отлично

2024-04-08 04:46 UTC, merged