KS-3-3 commit
decalsheggy/KotlinSprint pull request #13
Opened 2024-04-04 14:53 UTC by decalsheggy

2024-04-05 15:53 UTC, ievetrovdev requested changes

2024-04-05 15:53 UTC, ievetrovdev commented on src/main/kotlin/lesson_3/lesson3-task3.kt
> +        println("$number * $i = " + number * i)
Не соблюдено требование условия - функция println() должна вызываться один раз)

2024-04-05 15:53 UTC, ievetrovdev commented on src/main/kotlin/lesson_3/lesson3-task3.kt
> + которая вызывается один раз.*/
у тебя даже здесь это написано)

2024-04-05 16:13 UTC, decalsheggy commented on src/main/kotlin/lesson_3/lesson3-task3.kt
> + которая вызывается один раз.*/
А ой) я думала, что если в коде println() один раз записано, то это уже успех
Каждый раз думаю, что решила хорошо и почти всегда какие-то ошибки выскакивают эх

2024-04-05 16:13 UTC, decalsheggy commented on src/main/kotlin/lesson_3/lesson3-task3.kt
> + которая вызывается один раз.*/
Буду исправлять, вроде поняла

2024-04-05 16:57 UTC, decalsheggy commented on src/main/kotlin/lesson_3/lesson3-task3.kt
> + которая вызывается один раз.*/
Случилось какое-то текстовое наводнение, не уверена, что исправила правильно

2024-04-06 06:05 UTC, ievetrovdev approved these changes
Оба варианта рабочие и верное, хорошо что придумала их. Хотя по заданию предполагалось через trimMargin.
Все придет с опытом, только нужно обдумывать суть задания и не пропускать слова)

2024-04-08 04:47 UTC, merged