KS-3-5 commit
decalsheggy/KotlinSprint pull request #15
Opened 2024-04-04 16:22 UTC by decalsheggy

2024-04-05 17:19 UTC, decalsheggy commented
Наверное это можно оптимизировать, но я не нашла как, split пришлось два раза использовать

2024-04-06 06:10 UTC, ievetrovdev requested changes

2024-04-06 06:10 UTC, ievetrovdev commented on src/main/kotlin/lesson_3/lesson3-task5.kt
> +    val moveNumber = stringWhite.split(";")
Мы пользуемся сплит и обрати внимание на его сигнатуру. метод имеет ключевое слово vararg - то есть он может принимать произвольное количество параметров. то есть в данном случае разделителей. Подробнее тут https://metanit.com/kotlin/tutorial/3.2.php
что значит можно stringWhite.split("-", ";")

2024-04-06 06:40 UTC, decalsheggy commented on src/main/kotlin/lesson_3/lesson3-task5.kt
> +    val moveNumber = stringWhite.split(";")
Спасибо! Переделала

2024-04-06 15:17 UTC, ievetrovdev approved these changes

2024-04-08 04:50 UTC, merged