KS-4-4
decalsheggy/KotlinSprint pull request #19
Opened 2024-04-06 15:39 UTC by decalsheggy

2024-04-06 15:58 UTC, decalsheggy commented
К гиту приноровиться не могу, устроила путаницу с коммитами
Надеюсь проверке сильно не помешает

2024-04-07 05:33 UTC, ievetrovdev requested changes

2024-04-07 05:33 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task4.kt
> +    if (currentDay % 2 == 1) {
Лучше вынести нахождение четности (только четности) числа в отдельный флаг и применять его уже при выводе напрямую или с отрицанием (инвертируя). Также Boolean переменные принято называть isSomeSituation (не обязательно, но так код легче читается). Давай назовем этот флаг `isEvenDay`

2024-04-07 05:33 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task4.kt
> +    var isArms = true;
После создания флага все эти переменные можно будет удалить

2024-04-07 05:35 UTC, ievetrovdev requested changes

2024-04-07 05:35 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task2.kt
> +const val MIN_WEIGHT = 35
этот файл относится к заданию 4-2, давай его удалим отсюда. у тебя сейчас висит 13 мров. после получения аппрува его нужно мержить в мастер ветку и при создании новой ветки нужно проверять, чтобы она создавалась от мастера и при этом в нее были подтянуты все актуальные изменения

2024-04-08 05:50 UTC, ievetrovdev approved these changes

2024-04-08 10:51 UTC, merged