KS-4-5
decalsheggy/KotlinSprint pull request #20
Opened 2024-04-08 10:38 UTC by decalsheggy

2024-04-09 07:08 UTC, ievetrovdev requested changes

2024-04-09 07:08 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task5.kt
> +    val provision = 51
у тебя сейчас есть входные данные для экипажа и провизии, но где данные для повреждений корабля и погодных условий?

2024-04-09 07:08 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task5.kt
> +           /*val isGoSailing = ((IS_NO_DAMAGE)
этот кусок кода выглядит как лишний)

2024-04-09 10:45 UTC, decalsheggy commented on src/main/kotlin/lesson_4/lesson4_task5.kt
> +           /*val isGoSailing = ((IS_NO_DAMAGE)
И правда лишний

2024-04-10 07:12 UTC, ievetrovdev approved these changes

2024-04-11 04:11 UTC, merged