KS-5-1 commit
decalsheggy/KotlinSprint pull request #21
Opened 2024-04-08 11:46 UTC by decalsheggy

2024-04-09 14:33 UTC, ievetrovdev requested changes

2024-04-09 14:33 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task1.kt
> +    val sum = readLine()!!.toInt()
В данном случае лучше использовать функцию readln(), которая не будет выбрасывать исключение, если в нее прийдет null, а просто вернет строку (строка будет конфликтовать с приведением к целочисленному типу, но это другой кейс, важнее разобраться с нулябельностью)

2024-04-09 16:15 UTC, decalsheggy commented on src/main/kotlin/lesson_5/lesson5_task1.kt
> +    val sum = readLine()!!.toInt()
В теме нулябельности я пока плаваю, в теории вроде поняла, но на практике еще нужно будет разобраться) 
А так код подкорректировала

2024-04-10 07:21 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task1.kt
> +    val sum = readLine()!!.toInt()
с нуляберностью будет глава, пока что лучше избегать этого

2024-04-10 07:21 UTC, ievetrovdev approved these changes

2024-04-11 04:11 UTC, merged