KS-5-3 commit
decalsheggy/KotlinSprint pull request #23
Opened 2024-04-08 16:33 UTC by decalsheggy

2024-04-09 14:36 UTC, ievetrovdev requested changes

2024-04-09 14:36 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task3.kt
> +    val firstNumber = readLine()
лучше заменить на readln

2024-04-09 14:36 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task3.kt
> +    val arrayOfNumbers = arrayOf(number1, number2)
давай в этой задаче сделаем без списков. В будущем затронет и их

2024-04-09 14:36 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task3.kt
> +    if ((firstNumber in arrayOfNumbers) && (secondNumber in arrayOfNumbers) && firstNumber != secondNumber)
Просто такое использование через in не самое лучшее

2024-04-09 16:05 UTC, decalsheggy commented on src/main/kotlin/lesson_5/lesson5_task3.kt
> +    if ((firstNumber in arrayOfNumbers) && (secondNumber in arrayOfNumbers) && firstNumber != secondNumber)
Чисто визуально не очень? Или могут быть какие-то последствия из-за использования здесь in?

2024-04-10 07:20 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task3.kt
> +    if ((firstNumber in arrayOfNumbers) && (secondNumber in arrayOfNumbers) && firstNumber != secondNumber)
скорее это не оптимально по ресурсам проходить в массиве каждый раз. Работать с массивами нужно как можно меньшим количеством проходов

2024-04-10 07:20 UTC, ievetrovdev approved these changes

2024-04-11 04:12 UTC, merged