KS-1-3 Commit
decalsheggy/KotlinSprint pull request #3
Opened 2024-04-03 06:19 UTC by decalsheggy

2024-04-03 15:02 UTC, ievetrovdev requested changes

2024-04-03 15:02 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +    println("Время взлета: \n$year год \n$hour часов \n$minute минут")
В примере в ТЗ цифры начинаются с 0.
Вообще нормальная практика, если сервер присылает дату или время строкой.
Давай объявим строки и сделаем правильный формат)

2024-04-03 15:02 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +    var minute = 7
Учти комментарий из предыдущей задачи

2024-04-03 17:05 UTC, decalsheggy commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +    println("Время взлета: \n$year год \n$hour часов \n$minute минут")
Скорректировала

2024-04-04 07:36 UTC, ievetrovdev approved these changes
Отлично

2024-04-04 07:57 UTC, merged