KS-7-1 commit
decalsheggy/KotlinSprint pull request #34
Opened 2024-04-16 15:53 UTC by decalsheggy

2024-04-17 05:13 UTC, ievetrovdev requested changes

2024-04-17 05:13 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7-task1.kt
> +    val characters = "abcdefghijklmnopqrstuvwxyz0123456789"
в условии сказано что символы в пароле должны чередоваться, сейчас не получится это сделать) также диапазоны можно задавать таким образом: `'a'..'z'`

2024-04-17 05:38 UTC, decalsheggy commented on src/main/kotlin/lesson_7/lesson7-task1.kt
> +    val characters = "abcdefghijklmnopqrstuvwxyz0123456789"
Спасибо! Так 'a'..'z' конечно попроще, сразу как-то не додумалась)

2024-04-18 05:03 UTC, ievetrovdev approved these changes

2024-04-18 07:44 UTC, merged