KS-7-5 commit
decalsheggy/KotlinSprint pull request #35
Opened 2024-04-16 16:08 UTC by decalsheggy

2024-04-16 16:30 UTC, decalsheggy commented
Не получилось до конца решить задачку..
По одному из условий цифры и буквы должны располагаться в случайном порядке, а с моими костыльными методами, все пароли начинаются строго с цифры, строчной и заглавной букв)

2024-04-17 06:21 UTC, decalsheggy commented
В итоге включила в решение список из гарантированных символов, вроде теперь условиям соответствует
Хотя наверное есть более умное решение

2024-04-18 05:08 UTC, ievetrovdev requested changes

2024-04-18 05:08 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7-task5.kt
> +        password.append((numbers + lowercaseLetters + uppercaseLetters).random())
все отлично! только давай общий список символов не будем создавать на каждой итерации)

2024-04-18 07:57 UTC, decalsheggy commented on src/main/kotlin/lesson_7/lesson7-task5.kt
> +        password.append((numbers + lowercaseLetters + uppercaseLetters).random())
Хорошо)

2024-04-19 05:32 UTC, ievetrovdev approved these changes

2024-04-19 06:51 UTC, merged