KS-9-2 commit
decalsheggy/KotlinSprint pull request #41
Opened 2024-04-18 11:57 UTC by decalsheggy

2024-04-19 15:49 UTC, ievetrovdev requested changes

2024-04-19 15:49 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson9-task2.kt
> +    if (decision == "да") {
Давай еще учтем разный регистр, который может быть введен пользователем. Можно использовать метод сравнения у которого есть свойство ignoreCase

2024-04-19 16:31 UTC, decalsheggy commented on src/main/kotlin/lesson_9/lesson9-task2.kt
> +    if (decision == "да") {
Хорошо

2024-04-20 06:02 UTC, ievetrovdev approved these changes

2024-04-22 08:56 UTC, merged