KS-1-5 Commit
decalsheggy/KotlinSprint pull request #5
Opened 2024-04-03 07:14 UTC by decalsheggy

2024-04-03 15:05 UTC, ievetrovdev requested changes

2024-04-03 15:05 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    val howManyMin = howManySec / 60
Чтобы снизить риск ошибок, предлагаю все “голые” числа вынести в константу. Кроме того это [магические числа](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-04-03 15:05 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    println("время, проведенное в космосе: $howManyHours:$restMin:$restSec")
Вывод немного не верен, должно быть всегда по 2 символа. Предлагаю изучить функцию String.format()

2024-04-03 16:44 UTC, decalsheggy commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +    println("время, проведенное в космосе: $howManyHours:$restMin:$restSec")
Спасибо! Применила String.format(), полезная штука)

2024-04-04 07:39 UTC, ievetrovdev requested changes

2024-04-04 07:39 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task5.kt
> +const val SEC_IN_SPACE = 6480
Тут не совсем верно, 60 это константы потому что она никогда не будет меняться. в меняет всегда 60. 
6480 это уже не константа, время может изменится и программа все равно будет правильно работать, это же число можно менять в моменте работы программы.
Так что надо 6480 вынести обратно в переменную.

2024-04-04 14:45 UTC, ievetrovdev approved these changes

2024-04-05 07:47 UTC, merged