KS-11-1 commit
decalsheggy/KotlinSprint pull request #51
Opened 2024-04-23 11:24 UTC by decalsheggy

2024-04-24 14:29 UTC, ievetrovdev requested changes
В аннотации к уроку я упоминаю создавать классы в одном файле. Перемести плиз)

2024-04-24 14:29 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/task_1/UserData.kt
> +class UserData(val id: String, val login: String, val password: String, val message: Boolean = true) {
Не критично, но тут имеется ввиду e-mail со стринговым типом)

2024-04-24 14:44 UTC, decalsheggy commented
> В аннотации к уроку я упоминаю создавать классы в одном файле. Перемести плиз)

Извиняюсь, затуп словила, почему-то подумала, что классы достаточно в одну папку переместить
Исправлю

2024-04-25 09:52 UTC, ievetrovdev approved these changes

2024-04-28 12:55 UTC, merged