KS-12-2 commit
decalsheggy/KotlinSprint pull request #56
Opened 2024-04-26 11:51 UTC by decalsheggy

2024-04-27 07:14 UTC, ievetrovdev requested changes

2024-04-27 07:14 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12-task2.kt
> +class DayWeather(_nightWeather: Int, _dayWeather: Int, _rainDuringTheDay: Boolean) {
можно сразу объявлять переменные в конструкторе DayWeather(val nightWeather: Int)
Так же советую ставить запятую и в последнем элементе и каждый параметр писать со своей строки

2024-04-27 12:13 UTC, decalsheggy commented on src/main/kotlin/lesson_12/lesson12-task2.kt
> +class DayWeather(_nightWeather: Int, _dayWeather: Int, _rainDuringTheDay: Boolean) {
Хорошо, поняла

2024-04-28 07:14 UTC, ievetrovdev approved these changes

2024-04-28 12:56 UTC, merged