KS-12-5 commit
decalsheggy/KotlinSprint pull request #59
Opened 2024-04-26 12:20 UTC by decalsheggy

2024-04-27 07:18 UTC, ievetrovdev requested changes

2024-04-27 07:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12-task5.kt
> +    val allDays = mutableListOf<String>()
Тут прям много лишних списков, можно же создать один список объектов WeatherData и работать уже с ним, без всех остальных

2024-04-27 13:50 UTC, decalsheggy commented on src/main/kotlin/lesson_12/lesson12-task5.kt
> +    val allDays = mutableListOf<String>()
У меня просто в голове не укладывалось, что можно передать класс в качестве типов данных.. Но гугл говорит, что все типы данных в Kotlin являются объектами классов, так что все сошлось и стало чуточку проще, спасибо)
Код подправила

2024-04-28 07:16 UTC, ievetrovdev commented on src/main/kotlin/lesson_12/lesson12-task5.kt
> +    val allDays = mutableListOf<String>()
Отлично, самое главное в ООП понять это хорошо)

2024-04-28 07:16 UTC, ievetrovdev approved these changes

2024-05-06 09:16 UTC, merged