KS-13-5 commit
decalsheggy/KotlinSprint pull request #67
Opened 2024-04-28 16:50 UTC by decalsheggy

2024-04-30 17:18 UTC, ievetrovdev requested changes

2024-04-30 17:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson13-task5.kt
> +    val input = readln().toLongOrNull()
По условию:
> Если пользователь ввел что-либо, кроме цифр — программа падает

Давай не приводить к нулю, можно просто падать

2024-04-30 17:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson13-task5.kt
> +class PhoneBookData(val name: String, val phoneNumber: Long?, val company: String? = null) {
давай отформатируем конструктор, каждый параметр в новой строке:
```Kotlin
PhoneBookData(
        val name: String,
        val phoneNumber: Long?,
        val company: String? = null,
)
```

2024-05-01 14:40 UTC, ievetrovdev requested changes
Чтобы отловить ошибку воспользуйся блоком try catch. Подробнее о нем и о способе применения можно посмотреть [здесь](https://kotlinlang.org/docs/exceptions.html#exception-classes)

2024-05-01 15:44 UTC, decalsheggy commented
> Чтобы отловить ошибку воспользуйся блоком try catch. Подробнее о нем и о способе применения можно посмотреть [здесь](https://kotlinlang.org/docs/exceptions.html#exception-classes)

Спасибо, вроде получилось (в консоль выводит NumberFormatException)

2024-05-02 16:40 UTC, ievetrovdev approved these changes

2024-05-06 09:18 UTC, merged