KS11-5 commit
decalsheggy/KotlinSprint pull request #74
Opened 2024-05-02 13:24 UTC by decalsheggy

2024-05-04 08:31 UTC, ievetrovdev requested changes
Логика немного усложнена. Давай ограничимся только методами создания объектов внутри класса форум. То есть уберем прослойку из классов для фабрики

Метод должен одновременно создавать объект, генерируя для него айди, добавлять в список и возвращать созданный объект (чтобы использовать пользователя для создания сообщения)

2024-05-04 12:20 UTC, decalsheggy commented
Подправила, вроде оно работает
А еще(не по теме) проверь пожалуйста 5ю задачку по 14 теме, над ней тоже долго сидела и поздно скинула, хочу просто к следующему блоку перейти

2024-05-06 08:14 UTC, ievetrovdev approved these changes

2024-05-06 08:32 UTC, ievetrovdev approved these changes

2024-05-06 09:17 UTC, merged