KS-17-3 commit
decalsheggy/KotlinSprint pull request #83
Opened 2024-05-08 19:02 UTC by decalsheggy

2024-05-09 04:21 UTC, ievetrovdev requested changes

2024-05-09 04:21 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson17-task3.kt
> +    private val _name: String,
почему то у тебя 2 поля с нижними подчеркиваниями, а одно без них) давай везде их уберем, также как и `private val`, нам не нужно иметь к ним доступ снаружи

2024-05-09 04:21 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson17-task3.kt
> +    val name: String
к этому полю мы можем обратиться снаружи, его можно переименовать в `folderName`

2024-05-09 08:23 UTC, decalsheggy commented on src/main/kotlin/lesson_17/lesson17-task3.kt
> +    private val _name: String,
Немного не поняла, мы же как раз благодаря private val  не имеем к переменным доступ снаружи

2024-05-10 05:32 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson17-task3.kt
> +    private val _name: String,
я имел ввиду не делать эти аргументы свойствами, в таком варианте к ним также нельзя было бы обратиться)

```
class Package(
    name: String,
    numberOfFiles: Int,
    secretFlag: Boolean = true,
)
```

2024-05-10 05:33 UTC, ievetrovdev approved these changes

2024-05-13 07:04 UTC, merged