KS-17-5 commit
decalsheggy/KotlinSprint pull request #85
Opened 2024-05-09 15:21 UTC by decalsheggy

2024-05-10 06:00 UTC, ievetrovdev requested changes

2024-05-10 06:00 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson17-task5.kt
> +    val passwordInfo: String = password.replace(Regex("."), "*")
зачем нам 2 переменные с паролем? закрытый звездочками пароль мы можем получить при вызове геттера у `changedPassword`, например если сделать его таким образом `get() = "*".repeat(field.length)`

2024-05-10 06:00 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson17-task5.kt
> +class User(private var login: String, private val password: String) {
не обязательно делать входные аргументы свойствами, так как снаружи мы к ним не обращаемся 
`class User(login: String, password: String)`

2024-05-10 09:44 UTC, decalsheggy commented on src/main/kotlin/lesson_17/lesson17-task5.kt
> +    val passwordInfo: String = password.replace(Regex("."), "*")
А ой, жизнь себе усложняю видимо

2024-05-11 09:15 UTC, ievetrovdev requested changes

2024-05-11 09:15 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson17-task5.kt
> +    private val password = initialPassword
а зачем нам эти свойства если они дублируют входные данные и снаружи мы к ним обратиться не можем? лучше будет сделать таким образом:
```
var password: String
        get() = "*".repeat(password.length)
        set(value) {
            if (value != password) println("Вы не можете изменить пароль на $value.")
        }
```

и также для логина, тогда не будет создаваться лишних переменных

2024-05-11 12:49 UTC, decalsheggy commented on src/main/kotlin/lesson_17/lesson17-task5.kt
> +    private val password = initialPassword
Подправила, но если в точности как в примере код переписывать, то бесконечная рекурсия выходит

2024-05-12 05:14 UTC, ievetrovdev approved these changes

2024-05-13 07:06 UTC, merged