KS19-5 commit
decalsheggy/KotlinSprint pull request #95
Opened 2024-05-12 06:40 UTC by decalsheggy

2024-05-12 15:14 UTC, ievetrovdev requested changes

2024-05-12 15:14 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson19-task5.kt
> +    MAN("мужчина");
Предлагаю еще добавить объект ERROR или UNDEFINDED. чтобы предусмотреть варианты для обработки ошибки именно

2024-05-12 15:14 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson19-task5.kt
> +            if (gender != null) {
Тогда можно будет убрать эту проверку

2024-05-12 16:13 UTC, decalsheggy commented on src/main/kotlin/lesson_19/lesson19-task5.kt
> +    MAN("мужчина");
Кажется будто затрагиваем что-то на языке тестировщиков)

2024-05-14 08:13 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson19-task5.kt
> +    MAN("мужчина");
Скорее правило хорошего тона, учесть что пользователь что то сделает мне так и может сломать приложение) Тестировщик в конце концов все равно найдет этот момент и попросит исправить. Так что надо пытаться сразу учесть)

2024-05-14 08:14 UTC, ievetrovdev approved these changes

2024-05-17 09:22 UTC, merged