KS-20-4 commit
decalsheggy/KotlinSprint pull request #99
Opened 2024-05-13 08:32 UTC by decalsheggy

2024-05-13 19:13 UTC, ievetrovdev requested changes

2024-05-13 19:13 UTC, ievetrovdev commented on src/main/kotlin/lesson_20/lesson20-task4.kt
> +    val everyElement = listOfLambda.map { it.invoke("") }
в задании сказано нажать на четные элементы списка, а у тебя сейчас нажимается каждый)

2024-05-13 20:14 UTC, decalsheggy commented on src/main/kotlin/lesson_20/lesson20-task4.kt
> +    val everyElement = listOfLambda.map { it.invoke("") }
Видимо мозг скипнул слово, чтобы задачу было проще решить

2024-05-14 05:20 UTC, ievetrovdev approved these changes

2024-05-14 05:20 UTC, ievetrovdev commented on src/main/kotlin/lesson_20/lesson20-task4.kt
> +    val listOfLambda: List<(String) -> String> = listOfString.map { lambda ->
все супер, но на будущее тут можно было сделать такую лямбду `List<() -> String>,` тогда при вызове не пришлось бы передавать пустую строку `println(lambda.invoke())`

2024-05-14 08:59 UTC, decalsheggy commented on src/main/kotlin/lesson_20/lesson20-task4.kt
> +    val listOfLambda: List<(String) -> String> = listOfString.map { lambda ->
> все супер, но на будущее тут можно было сделать такую лямбду `List<() -> String>,` тогда при вызове не пришлось бы передавать пустую строку `println(lambda.invoke())`

хорошо, поняла

2024-05-17 09:24 UTC, merged